Repository yourCozy/cozy-iOS, pull requests merged in 2020-08, with the labels that each got.

#2 프로젝트 초기 설정
  cozy/.swiftlint.yml
  cozy/Podfile
  cozy/Podfile.lock
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  cozy/cozy.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  cozy/cozy.xcworkspace/contents.xcworkspacedata
  cozy/cozy.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  cozy/cozy/Info.plist
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/Contents.json
  cozy/cozy/Resource/Base.lproj/LaunchScreen.storyboard
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Base.lproj/Main.storyboard
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/Extensions/UIColor+Extensions.swift
  cozy/cozy/Source/Service/APIConstants.swift
  cozy/cozy/Source/Service/NetworkResult.swift
  cozy/cozy/Source/ViewControllers/Activity/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Map/MapVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/RecommendVC.swift
  cozy/cozy/Source/ViewControllers/ViewController.swift
  cozy/cozy/Supporting Files/AppDelegate.swift
  cozy/cozy/Supporting Files/SceneDelegate.swift
  cozy/cozy/Supporting Files/cozy.xcdatamodeld/.xccurrentversion
  cozy/cozy/Supporting Files/cozy.xcdatamodeld/cozy.xcdatamodel/contents
Labels: iOS

#11 Update: AutoLayout & Font
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Source/ViewControllers/Activity/ActivityVC.swift
Labels: UI, iOS

#12 Feat/jiyoung
  .gitignore
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/iconevent.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/iconevent.imageset/iconevent.png
  cozy/cozy/Resource/Assets.xcassets/iconevent.imageset/iconevent@2x.png
  cozy/cozy/Resource/Assets.xcassets/iconevent.imageset/iconevent@3x.png
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/ViewControllers/Mypage/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/recentCell.swift
Labels: UI, iOS

#15 Activity View : CollectionView -> StackView
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
Labels: UI, iOS

#16 MapVC 다시 그리기 ^^...
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/icon/iconfeature62.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/icon/iconmore.imageset/iconmore.png
  cozy/cozy/Resource/Assets.xcassets/icon/iconmore.imageset/iconmore@2x.png
  cozy/cozy/Resource/Assets.xcassets/icon/iconmore.imageset/iconmore@3x.png
  cozy/cozy/Resource/Assets.xcassets/icon/iconsavewhite.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/asdfdghfgjhj.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/asdfdghfgjhj.imageset/asdfdghfgjhj.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/asdfdghfgjhj.imageset/asdfdghfgjhj@2x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/asdfdghfgjhj.imageset/asdfdghfgjhj@3x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconactivity.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconactivity.imageset/tapiconactivity.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconactivity.imageset/tapiconactivity@2x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconactivity.imageset/tapiconactivity@3x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmappressed.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmappressed.imageset/tapiconmappressed.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmappressed.imageset/tapiconmappressed@2x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmappressed.imageset/tapiconmappressed@3x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmyinfo.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmyinfo.imageset/tapiconmyinfo.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmyinfo.imageset/tapiconmyinfo@2x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconmyinfo.imageset/tapiconmyinfo@3x.png
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconrecommend.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/tapicon/tapiconrecommend.imageset/tapiconrecommend@3x.png
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/Extensions/UIView+Extensions.swift
  cozy/cozy/Source/ViewControllers/Map/MapListCell.swift
  cozy/cozy/Source/ViewControllers/Map/MapSelectCell.swift
  cozy/cozy/Source/ViewControllers/Map/MapVC.swift
  cozy/cozy/Source/ViewControllers/Map/addressCell.swift
Labels: UI, iOS

#18 서점리스트 뷰 작업
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/ajeetMestryUBhpOiHnazMUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash.png
  cozy/cozy/Resource/Assets.xcassets/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash@2x.png
  cozy/cozy/Resource/Assets.xcassets/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash@3x.png
  cozy/cozy/Resource/Assets.xcassets/buttonyellow73.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/buttonyellow73.imageset/buttonyellow73.png
  cozy/cozy/Resource/Assets.xcassets/buttonyellow73.imageset/buttonyellow73@2x.png
  cozy/cozy/Resource/Assets.xcassets/buttonyellow73.imageset/buttonyellow73@3x.png
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Source/ViewControllers/Activity/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/BookStoreData.swift
Labels: UI, iOS

#20 feat/jaeuk
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/buttonyellow327.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/buttonyellow327.imageset/buttonyellow327.png
  cozy/cozy/Resource/Assets.xcassets/buttonyellow327.imageset/buttonyellow327@2x.png
  cozy/cozy/Resource/Assets.xcassets/buttonyellow327.imageset/buttonyellow327@3x.png
  cozy/cozy/Resource/Assets.xcassets/raychanKJq6CDyodAmUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash.png
  cozy/cozy/Resource/Assets.xcassets/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash@2x.png
  cozy/cozy/Resource/Assets.xcassets/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash@3x.png
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/ActivityRecommendVC.swift
Labels: UI, iOS

#21 update scrollview
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/ViewControllers/Mypage/MypageVC.swift
Labels: UI, iOS

#22 BookDetailVC 생성
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/ajeetMestryUBhpOiHnazMUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/buttonyellow327.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/ajeetMestryUBhpOiHnazMUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash@2x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/ajeetMestryUBhpOiHnazMUnsplash.imageset/ajeetMestryUBhpOiHnazMUnsplash@3x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow327.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow327.imageset/buttonyellow327.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow327.imageset/buttonyellow327@2x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow327.imageset/buttonyellow327@3x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow73.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow73.imageset/buttonyellow73.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow73.imageset/buttonyellow73@2x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/buttonyellow73.imageset/buttonyellow73@3x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/raychanKJq6CDyodAmUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/sampleImage/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash@2x.png
  cozy/cozy/Resource/Assets.xcassets/sampleImage/raychanKJq6CDyodAmUnsplash.imageset/raychanKJq6CDyodAmUnsplash@3x.png
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/BookDetail.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/Extensions/NSObject+Extensions.swift
  cozy/cozy/Source/ViewControllers/Map/Cell/BookListCell.swift
  cozy/cozy/Source/ViewControllers/Map/Cell/BookListCell.xib
  cozy/cozy/Source/ViewControllers/Map/Cell/MapSelectCell.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/NavBar/MainNavController.swift
  cozy/cozy/Source/ViewControllers/NavBar/MypageNavController.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/bookstoreCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/recommendCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, iOS

#23 Feat/jaeuk
  cozy/cozy/Resource/Assets.xcassets/2.imageset/2.png
  cozy/cozy/Resource/Assets.xcassets/2.imageset/2@2x.png
  cozy/cozy/Resource/Assets.xcassets/2.imageset/2@3x.png
  cozy/cozy/Resource/Assets.xcassets/2.imageset/Contents.json
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug, iOS
