Repository yourCozy/cozy-iOS, pull requests merged in 2020-09, with the labels that each got.

#31 Feat/jaeuk
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/DeadLineTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/Model/BookStoreData.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, iOS

#32 Modify onboarding, Update Interest
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/OnboardingVC.swift
Labels: UI, iOS

#33 Feat/jaeuk
  cozy/Podfile.lock
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/imageonboarding1.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding1.imageset/imageonboarding1.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding1.imageset/imageonboarding1@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding1.imageset/imageonboarding1@3x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2@3x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3@3x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4@3x.png
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/SlideOnboarding.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/PageVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc0.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc1.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc2.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc3.swift
Labels: UI, iOS

#35 DetailVC 완성 🔥
  cozy/Podfile.lock
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/ViewControllers/Map/VC/MapSelectVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/bookstoreCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, iOS

#36 Delete: Onboarding Intro.. Fuck..
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/imageonboarding1.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding2.imageset/imageonboarding2@3x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding3.imageset/imageonboarding3@3x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4@2x.png
  cozy/cozy/Resource/Assets.xcassets/imageonboarding4.imageset/imageonboarding4@3x.png
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/SlideOnboarding.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/PageVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc0.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc1.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc2.swift
  cozy/cozy/Source/ViewControllers/Onboarding/vc3.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/bookstoreCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, iOS

#41 success kakao login
  cozy/cozy/Info.plist
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Supporting Files/AppDelegate.swift
Labels: kakao

#42 Feat/jiyoung
  cozy/5.1
  cozy/Podfile.lock
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/Extensions/UIColor+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/NoticeVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
Labels: UI

#43 APIConstants🚨
  cozy/cozy/Source/Service/APIConstants.swift
Labels: API, Server, iOS

#45 Get method success
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Source/Service/APIConstants.swift
  cozy/cozy/Source/Service/ActivityListService.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/Model/ActivityListModel.swift
  cozy/cozy/Source/ViewControllers/Activity/Model/BookStoreData.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/NoticeVC.swift
Labels: API, Server, iOS

#46 DetailVC 기능 추가
  cozy/cozy/Info.plist
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/bookstoreCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, iOS

#48 네이버 지도 연결하기
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Info.plist
  cozy/cozy/Resource/Assets.xcassets/buttonremove40.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/buttonremove40.imageset/buttonremove40.png
  cozy/cozy/Resource/Assets.xcassets/buttonremove40.imageset/buttonremove40@2x.png
  cozy/cozy/Resource/Assets.xcassets/buttonremove40.imageset/buttonremove40@3x.png
  cozy/cozy/Resource/Assets.xcassets/iconkakaoothers24X22.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/iconkakaoothers24X22.imageset/iconkakaoothers24X22.png
  cozy/cozy/Resource/Assets.xcassets/iconkakaoothers24X22.imageset/iconkakaoothers24X22@2x.png
  cozy/cozy/Resource/Assets.xcassets/iconkakaoothers24X22.imageset/iconkakaoothers24X22@3x.png
  cozy/cozy/Resource/Storyboard/Login/Login.storyboard
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/ViewControllers/Login/KakaoLoginVC.swift
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
Labels: API, Naver, iOS

#49 중간 확인
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/iconfold8X14.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/iconfold8X14.imageset/iconfold8X14.png
  cozy/cozy/Resource/Assets.xcassets/iconfold8X14.imageset/iconfold8X14@2x.png
  cozy/cozy/Resource/Assets.xcassets/iconfold8X14.imageset/iconfold8X14@3x.png
  cozy/cozy/Resource/Assets.xcassets/iconmore8X14.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/iconmore8X14.imageset/iconmore8X14.png
  cozy/cozy/Resource/Assets.xcassets/iconmore8X14.imageset/iconmore8X14@2x.png
  cozy/cozy/Resource/Assets.xcassets/iconmore8X14.imageset/iconmore8X14@3x.png
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/noticeTitleCell.swift
Labels: UI, iOS

#50 logout mypage
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/ViewControllers/Mypage/MypageVC.swift
Labels: UI, iOS

#53 메인 책방 추천 API 연결
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Info.plist
  cozy/cozy/Source/API/ResponseModel/RecommendListModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/ActivityListService.swift
  cozy/cozy/Source/API/Services/NetworkResult.swift
  cozy/cozy/Source/API/Services/RecommendListService.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, Server, iOS

#56 Recommend Feed Service(), Model
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/API/ResponseModel/RecommendFeedModel.swift
  cozy/cozy/Source/API/Services/RecommendFeedService.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: API, Server, iOS

#59 지도 탭 API 모두 연결!
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Source/API/ResponseModel/MapCountModel.swift
  cozy/cozy/Source/API/ResponseModel/MapListModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/MapCountService.swift
  cozy/cozy/Source/API/Services/MapListService.swift
  cozy/cozy/Source/ViewControllers/Map/Cell/MapSelectCell.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapSelectVC.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
Labels: API, Server, iOS

#63 카카오 로그인 API 연결
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Info.plist
  cozy/cozy/Source/API/ResponseModel/KakaoLoginModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/KakaoLoginService.swift
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
Labels: API, iOS, kakao

#64 애플 로그인 성공~!~!
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/cozy.entitlements
Labels: API, Apple

#66 이것저것 버그 수정
  cozy/cozy/Resource/Storyboard/Onboarding/OnboardingIntro.storyboard
  cozy/cozy/Source/API/ResponseModel/KakaoLoginModel.swift
  cozy/cozy/Source/API/Services/KakaoLoginService.swift
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/Cell/onboardcell1.xib
  cozy/cozy/Source/ViewControllers/Onboarding/Cell/onboardcell2.xib
  cozy/cozy/Source/ViewControllers/Onboarding/Cell/onboardcell3.xib
  cozy/cozy/Source/ViewControllers/Onboarding/Cell/onboardcell4.xib
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingIntroVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, Server, bug, kakao

#70 I'm King Fisher
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Source/API/ResponseModel/ActivityDetailModel.swift
  cozy/cozy/Source/API/Services/ActivityDetailService.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/DisplayDetailCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Model/DisplayDetailData.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: API, iOS

#73 FIX: small errors
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/API/Services/ActivityListService.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: bug

#74 활동탭 끝!
  cozy/cozy/Source/API/ResponseModel/ActivityListModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/ActivityDetailService.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: API, Server, UI, bug

#77 디데이 지난 데이터 제거 + 취향선택 서버통신
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/null/Contents.json
  cozy/cozy/Resource/Fonts/NanumSquareRoundB.ttf
  cozy/cozy/Resource/Fonts/NanumSquareRoundEB.ttf
  cozy/cozy/Resource/Fonts/NanumSquareRoundL.ttf
  cozy/cozy/Resource/Fonts/NanumSquareRoundR.ttf
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/API/ResponseModel/TastesModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/TastesService.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: API, iOS

#80 북마크 버그 해결 완료
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/null/Contents.json
  cozy/cozy/Resource/Storyboard/Onboarding/OnboardingIntro.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/Splash.storyboard
  cozy/cozy/Source/API/Services/MapListService.swift
  cozy/cozy/Source/API/Services/RecommendListService.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/SplashVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, Server, bug

#83 활동상세뷰 댓글 시작~
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/line1X11.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/line1X11.imageset/line1X11.png
  cozy/cozy/Resource/Assets.xcassets/line1X11.imageset/line1X11@2x.png
  cozy/cozy/Resource/Assets.xcassets/line1X11.imageset/line1X11@3x.png
  cozy/cozy/Resource/Assets.xcassets/line375X8Lightgray.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/line375X8Lightgray.imageset/line375X8Lightgray.png
  cozy/cozy/Resource/Assets.xcassets/line375X8Lightgray.imageset/line375X8Lightgray@2x.png
  cozy/cozy/Resource/Assets.xcassets/line375X8Lightgray.imageset/line375X8Lightgray@3x.png
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/API/ResponseModel/CommentModel.swift
  cozy/cozy/Source/API/ResponseModel/TastesModel.swift
  cozy/cozy/Source/API/Services/TastesService.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/CommentCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug, iOS

#88 온보딩 버튼 3개 3개 제한 성공~~~
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
Labels: UI, iOS

#95 마이페이지 버그 수정
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
Labels: API, UI, bug

#97 활동탭 UIView touch event
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
Labels: UI, iOS

#98 마이페이지, 상세뷰 디폴트 값 수정
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/Extensions/UIImageView+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, UI, bug

#103 MapVC nil 처리, 이벤트/공지사항 뷰 수정
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/ViewControllers/MainTabVC.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/Cell/eventTitleCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/Cell/noticeContentCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/Model/EventModel.swift
  cozy/cozy/Source/ViewControllers/Mypage/Model/NoticeModel.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/EventVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/NoticeVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, bug, enhancement

#105 UPDATE: 활동탭 플로우 백버튼 업뎃
  cozy/cozy/Source/API/Services/ActivityDetailService.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, iOS

#108 온보딩 인트로 추가
  cozy/cozy/Info.plist
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/SplashVC.swift
Labels: bug, iOS

#109 최근 본 책방 버그 해결, 각종 이미지 nil 처리
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/120-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40-2.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/58-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/80-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/API/ResponseModel/MypageRecentModel.swift
  cozy/cozy/Source/API/Services/MypageRecentService.swift
  cozy/cozy/Source/ViewControllers/Map/Cell/BookListCell.xib
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, UI, bug

#110 FIX 각종 BUGS
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/imageNull.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageNull.imageset/imageNull.png
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/API/ResponseModel/ActivityDetailModel.swift
  cozy/cozy/Source/API/ResponseModel/ActivityListModel.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/CommentCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/DisplayDetailCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug

#111 각종 버그 수정
  cozy/cozy/Resource/Storyboard/Login/Login.storyboard
  cozy/cozy/Resource/Storyboard/Map/Map.storyboard
  cozy/cozy/Source/API/ResponseModel/MypageInterestModel.swift
  cozy/cozy/Source/Extensions/NSNotification+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, bug

#112 FIX: BUGS...
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: bug

#113 fix: interestVC url
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/API/Services/MypageInterestService.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/recommendCell.swift
Labels: API, bug

#114 Fix: bugs~
  cozy/cozy/Resource/Assets.xcassets/imageNull.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/imageNull.imageset/imageNull.png
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: bug

#115 Fix Bugs~
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/API/Services/ActivityDetailService.swift
  cozy/cozy/Source/API/Services/RecommendActivityService.swift
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/DisplayDetailCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: bug

#116 FIX: BUGS...
  cozy/cozy/Source/API/ResponseModel/ActivityListModel.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
Labels: bug

#118 ADD: label for no image
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/DisplayDetailCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug

#119 fix: mapVC, recommendVC nil
  cozy/cozy/Resource/Storyboard/Base.lproj/Main.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/ViewControllers/Map/Cell/BookListCell.swift
  cozy/cozy/Source/ViewControllers/Map/Cell/BookListCell.xib
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/bookstoreCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: bug

#121 UPDATE: 코드정리
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: enhancement, iOS

#124 마이페이지, 지도탭, 상세뷰 버그 수정
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Source/API/Services/BookstoreDetailService.swift
  cozy/cozy/Source/API/Services/MypageRecentService.swift
  cozy/cozy/Source/API/Services/RecommendActivityService.swift
  cozy/cozy/Source/API/Services/TastesService.swift
  cozy/cozy/Source/API/Services/UpdateInterestService.swift
  cozy/cozy/Source/Extensions/NSNotification+Extensions.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapSelectVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/Cell/eventContentCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/Cell/noticeTitleCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/Cell/recentCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
  cozy/cozy/cozy.entitlements
Labels: API, UI, bug

#125 데이터 nil 처리
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/Cell/ActivityTableViewCell.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug, iOS

#127 Dark mode Control
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Info.plist
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, bug, iOS

#128 UPDATE: print문 제거
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
Labels: iOS

#129 최근 본 책방 API 수정, 불투명도 조절
  cozy/cozy/Resource/Assets.xcassets/icon/blackicon.imageset/1x.png
  cozy/cozy/Resource/Assets.xcassets/icon/blackicon.imageset/2x.png
  cozy/cozy/Resource/Assets.xcassets/icon/blackicon.imageset/3x.png
  cozy/cozy/Resource/Assets.xcassets/icon/blackicon.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/icon/line1X11.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/icon/line1X11.imageset/line1X11.png
  cozy/cozy/Resource/Assets.xcassets/icon/line1X11.imageset/line1X11@2x.png
  cozy/cozy/Resource/Assets.xcassets/icon/line1X11.imageset/line1X11@3x.png
  cozy/cozy/Resource/Assets.xcassets/icon/line375X8Lightgray.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/icon/line375X8Lightgray.imageset/line375X8Lightgray.png
  cozy/cozy/Resource/Assets.xcassets/icon/line375X8Lightgray.imageset/line375X8Lightgray@2x.png
  cozy/cozy/Resource/Assets.xcassets/icon/line375X8Lightgray.imageset/line375X8Lightgray@3x.png
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Source/API/Services/MypageRecentService.swift
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: API, Server, UI, bug

#134 리드미 수정
  README.md
  screenshot/01.png
  screenshot/02.png
  screenshot/03.png
  screenshot/04.png
  screenshot/05.png
  screenshot/appicon.png
  screenshot/applogo.png
Labels: documentation

#137 Sprint1 버그 수정
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Login/LoginVC.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/SplashVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
Labels: UI, bug

#140 활동상세뷰 수정작업 시작
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Info.plist
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/120-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40-2.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/58-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/80-1.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  cozy/cozy/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
Labels: UI, iOS

#141 레이아웃 우수수 수정
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Recommend/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Mypage/Cell/recentCell.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/InterestVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.swift
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Recommend/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/BookDetailVC.swift
Labels: UI, bug
