Repository yourCozy/cozy-iOS, pull requests merged in 2020-10, with the labels that each got.

#149 FIX: ActivityRecommend Collectionview isHidden
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/kendyleNelsenWWuF2NlQ2OUnsplash.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/kendyleNelsenWWuF2NlQ2OUnsplash.imageset/kendyleNelsenWWuF2NlQ2OUnsplash.png
  cozy/cozy/Resource/Assets.xcassets/kendyleNelsenWWuF2NlQ2OUnsplash.imageset/kendyleNelsenWWuF2NlQ2OUnsplash@2x.png
  cozy/cozy/Resource/Assets.xcassets/kendyleNelsenWWuF2NlQ2OUnsplash.imageset/kendyleNelsenWWuF2NlQ2OUnsplash@3x.png
  cozy/cozy/Resource/Storyboard/Activity/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Recommend/Cell/commentCell.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI

#151 UPDATE: activity tab - alert view, no data
  cozy/cozy/Resource/Storyboard/Activity/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI, iOS

#156 검색 뷰 마무리 + API 연결 (진행중)
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Search/Search.storyboard
  cozy/cozy/Source/API/ResponseModel/SearchListModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/SearchService.swift
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Search/Cell/SearchListCell.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchListVC.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchVC.swift
Labels: API, UI

#157 버그 잡기
  cozy/cozy/Resource/Storyboard/Activity/ActivityList.storyboard
  cozy/cozy/Resource/Storyboard/Activity/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityListVC.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
Labels: UI, bug

#158 ADD: Logout storyboard
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Assets.xcassets/buttonroundyellow42X24.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/buttonroundyellow42X24.imageset/buttonroundyellow42X24.png
  cozy/cozy/Resource/Assets.xcassets/buttonroundyellow42X24.imageset/buttonroundyellow42X24@2x.png
  cozy/cozy/Resource/Assets.xcassets/buttonroundyellow42X24.imageset/buttonroundyellow42X24@3x.png
  cozy/cozy/Resource/Assets.xcassets/iconcamera.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/iconcamera.imageset/iconcamera.png
  cozy/cozy/Resource/Assets.xcassets/iconcamera.imageset/iconcamera@2x.png
  cozy/cozy/Resource/Assets.xcassets/iconcamera.imageset/iconcamera@3x.png
  cozy/cozy/Resource/Assets.xcassets/linelightgray.imageset/Contents.json
  cozy/cozy/Resource/Assets.xcassets/linelightgray.imageset/linelightgray.png
  cozy/cozy/Resource/Assets.xcassets/linelightgray.imageset/linelightgray@2x.png
  cozy/cozy/Resource/Assets.xcassets/linelightgray.imageset/linelightgray@3x.png
  cozy/cozy/Resource/Storyboard/Mypage/Logout.storyboard
Labels: API, UI, iOS

#159 로그아웃 성공
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Mypage/Logout.storyboard
  cozy/cozy/Source/API/ResponseModel/LogoutModel.swift
  cozy/cozy/Source/API/Services/APIConstants.swift
  cozy/cozy/Source/API/Services/LogoutService.swift
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/LogoutVC.swift
Labels: UI

#160 검색 API 완성
  cozy/cozy.xcodeproj/project.pbxproj
  cozy/cozy/Resource/Storyboard/Recommend/Recommend.storyboard
  cozy/cozy/Resource/Storyboard/Search/Search.storyboard
  cozy/cozy/Source/Extensions/NSNotification+Extensions.swift
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell1.swift
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell1.xib
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell2.swift
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell2.xib
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell3.swift
  cozy/cozy/Source/ViewControllers/Detail/Cell/detailCell3.xib
  cozy/cozy/Source/ViewControllers/Detail/VC/BookDetailVC.swift
  cozy/cozy/Source/ViewControllers/Map/VC/MapVC.swift
  cozy/cozy/Source/ViewControllers/Recommend/VC/RecommendVC.swift
  cozy/cozy/Source/ViewControllers/Search/Cell/SearchListCell.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchListVC.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchVC.swift
Labels: API, Server

#161 온보딩 갈아엎기
  cozy/cozy/Resource/Storyboard/Mypage/Mypage.storyboard
  cozy/cozy/Resource/Storyboard/Onboarding/Onboarding.storyboard
  cozy/cozy/Source/Extensions/UIButton+Extensions.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/MypageVC.swift
  cozy/cozy/Source/ViewControllers/Onboarding/VC/OnboardingVC.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchListVC.swift
  cozy/cozy/Source/ViewControllers/Search/VC/SearchVC.swift
Labels: UI, bug, enhancement

#162 UPDATE: Logout view - UI
  cozy/cozy/Resource/Storyboard/Activity/Activity.storyboard
  cozy/cozy/Resource/Storyboard/Mypage/Logout.storyboard
  cozy/cozy/Source/ViewControllers/Activity/VC/ActivityVC.swift
  cozy/cozy/Source/ViewControllers/Mypage/VC/LogoutVC.swift
Labels: UI

#164 UPDATE: 찐막 - 댓글테이블뷰 임시 제거
  cozy/cozy/Resource/Storyboard/Activity/ActivityRecommend.storyboard
  cozy/cozy/Source/ViewControllers/Recommend/VC/ActivityRecommendVC.swift
Labels: UI
